apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init.sql: |
    CREATE DATABASE invoice_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE subscription_db;
    CREATE DATABASE user_auth_db;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE invoice_db TO plateforme_user;
    GRANT ALL PRIVILEGES ON DATABASE payment_db TO plateforme_user;
    GRANT ALL PRIVILEGES ON DATABASE subscription_db TO plateforme_user;
    GRANT ALL PRIVILEGES ON DATABASE user_auth_db TO plateforme_user;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO plateforme_user;
