apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: yassmineg/plateforme-subscription:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/subscription_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: plateforme-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plateforme-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: KEYCLOAK_BASE_URL
              value: http://keycloak:8080
            - name: SPRING_SQL_INIT_MODE
              value: never
