apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
        - name: user-auth-service
          image: grassa77/plateforme-userauth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/user_auth_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: plateforme-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plateforme-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: http://keycloak:8080
            - name: KEYCLOAK_REALM
              value: plateforme-electronique
            - name: KEYCLOAK_RESOURCE
              value: user-auth-service
            - name: KEYCLOAK_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: plateforme-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: SPRING_SQL_INIT_MODE
              value: never
